export const ProductsData = [
  {
    vin: 'ee8a89d8',
    brand: 'Fiat',
    year: 1987,
    color: 'Maroon',
  },
  {
    vin: '642b3edc',
    brand: 'Renault',
    year: 1968,
    color: 'White',
  },
  {
    vin: '19ec7580',
    brand: 'Renault',
    year: 1981,
    color: 'Black',
  },
  {
    vin: '39980f30',
    brand: 'VW',
    year: 1986,
    color: 'Red',
  },
  {
    vin: 'ec9cc4e4',
    brand: 'Fiat',
    year: 1981,
    color: 'Brown',
  },
  {
    vin: '09a06548',
    brand: 'VW',
    year: 1965,
    color: 'Green',
  },
  {
    vin: '05c47246',
    brand: 'Mercedes',
    year: 2007,
    color: 'Blue',
  },
  {
    vin: 'a9cb87aa',
    brand: 'Fiat',
    year: 1962,
    color: 'Green',
  },
  {
    vin: 'eae758fa',
    brand: 'BMW',
    year: 1999,
    color: 'Yellow',
  },
  {
    vin: '1241c403',
    brand: 'Jaguar',
    year: 1964,
    color: 'Yellow',
  },
  {
    vin: '13f853a7',
    brand: 'Honda',
    year: 2006,
    color: 'White',
  },
  {
    vin: '447d9ed9',
    brand: 'Jaguar',
    year: 2005,
    color: 'Orange',
  },
  {
    vin: '78fa052e',
    brand: 'Jaguar',
    year: 1990,
    color: 'Orange',
  },
  {
    vin: '8b77772a',
    brand: 'Mercedes',
    year: 1991,
    color: 'Blue',
  },
  {
    vin: '23ba7e86',
    brand: 'Honda',
    year: 1975,
    color: 'Yellow',
  },
  {
    vin: '9bacb32d',
    brand: 'Volvo',
    year: 1968,
    color: 'Brown',
  },
  {
    vin: '62094d91',
    brand: 'Mercedes',
    year: 1962,
    color: 'Green',
  },
  {
    vin: 'dc7003f4',
    brand: 'Jaguar',
    year: 1976,
    color: 'Maroon',
  },
  {
    vin: '08607aef',
    brand: 'Mercedes',
    year: 1987,
    color: 'Maroon',
  },
  {
    vin: '45eee33a',
    brand: 'BMW',
    year: 1980,
    color: 'Silver',
  },
  {
    vin: 'f199ec5c',
    brand: 'Jaguar',
    year: 1961,
    color: 'Green',
  },
  {
    vin: 'b34cd9e8',
    brand: 'VW',
    year: 1993,
    color: 'Silver',
  },
  {
    vin: '54b20b02',
    brand: 'Renault',
    year: 1967,
    color: 'Brown',
  },
  {
    vin: '5dd8766e',
    brand: 'Honda',
    year: 1998,
    color: 'Orange',
  },
  {
    vin: 'df50ce22',
    brand: 'Mercedes',
    year: 1964,
    color: 'White',
  },
  {
    vin: 'ecb3e9e1',
    brand: 'Honda',
    year: 2003,
    color: 'Silver',
  },
  {
    vin: '750d731d',
    brand: 'Renault',
    year: 1962,
    color: 'Blue',
  },
  {
    vin: 'bec38cf4',
    brand: 'Renault',
    year: 1960,
    color: 'Blue',
  },
  {
    vin: 'b7752002',
    brand: 'Jaguar',
    year: 1964,
    color: 'Black',
  },
  {
    vin: '315fe9c4',
    brand: 'Fiat',
    year: 1985,
    color: 'Red',
  },
  {
    vin: 'be65f786',
    brand: 'Mercedes',
    year: 1963,
    color: 'Orange',
  },
  {
    vin: '786a7d57',
    brand: 'Mercedes',
    year: 2003,
    color: 'Black',
  },
  {
    vin: 'a3aee412',
    brand: 'Volvo',
    year: 2003,
    color: 'Maroon',
  },
  {
    vin: '749e6bdd',
    brand: 'Audi',
    year: 1995,
    color: 'Brown',
  },
  {
    vin: '8cc40f50',
    brand: 'BMW',
    year: 1961,
    color: 'Brown',
  },
  {
    vin: '5de63a6f',
    brand: 'Renault',
    year: 1961,
    color: 'White',
  },
  {
    vin: 'bdae1e20',
    brand: 'Jaguar',
    year: 2008,
    color: 'Blue',
  },
  {
    vin: '290cc891',
    brand: 'VW',
    year: 1992,
    color: 'Brown',
  },
  {
    vin: '007e1014',
    brand: 'Renault',
    year: 1966,
    color: 'Black',
  },
  {
    vin: '429c502d',
    brand: 'Honda',
    year: 1995,
    color: 'Silver',
  },
  {
    vin: 'c336f9b6',
    brand: 'Honda',
    year: 1991,
    color: 'Maroon',
  },
  {
    vin: 'a6783ba3',
    brand: 'Honda',
    year: 2004,
    color: 'Yellow',
  },
  {
    vin: '2ddaf8d5',
    brand: 'Volvo',
    year: 1982,
    color: 'Blue',
  },
  {
    vin: 'c09c4b15',
    brand: 'VW',
    year: 1991,
    color: 'Blue',
  },
  {
    vin: '4609844c',
    brand: 'Honda',
    year: 1972,
    color: 'Black',
  },
  {
    vin: '8db7df27',
    brand: 'Audi',
    year: 1982,
    color: 'Blue',
  },
  {
    vin: 'dcc58086',
    brand: 'Audi',
    year: 2001,
    color: 'Brown',
  },
  {
    vin: 'f1274cbe',
    brand: 'Fiat',
    year: 1995,
    color: 'Silver',
  },
  {
    vin: '0858a5d4',
    brand: 'Renault',
    year: 1992,
    color: 'Green',
  },
  {
    vin: 'c2d42bb6',
    brand: 'Volvo',
    year: 1972,
    color: 'Green',
  },
  {
    vin: '5535cd5a',
    brand: 'Renault',
    year: 1980,
    color: 'Silver',
  },
  {
    vin: 'e3313e1e',
    brand: 'Honda',
    year: 2009,
    color: 'Orange',
  },
  {
    vin: 'f4dea691',
    brand: 'BMW',
    year: 2002,
    color: 'Brown',
  },
  {
    vin: 'ec15a449',
    brand: 'Honda',
    year: 1990,
    color: 'Yellow',
  },
  {
    vin: '80b74a0e',
    brand: 'BMW',
    year: 1979,
    color: 'Yellow',
  },
  {
    vin: '513fe268',
    brand: 'Honda',
    year: 1987,
    color: 'White',
  },
  {
    vin: '6934c8f8',
    brand: 'Renault',
    year: 1989,
    color: 'Red',
  },
  {
    vin: '6a4c3ad0',
    brand: 'Honda',
    year: 1994,
    color: 'Yellow',
  },
  {
    vin: 'e0acd7b5',
    brand: 'Mercedes',
    year: 1965,
    color: 'Red',
  },
  {
    vin: '2f31ac35',
    brand: 'Jaguar',
    year: 1991,
    color: 'Brown',
  },
  {
    vin: '36104237',
    brand: 'VW',
    year: 1992,
    color: 'Silver',
  },
  {
    vin: '5be099b4',
    brand: 'BMW',
    year: 1991,
    color: 'Yellow',
  },
  {
    vin: 'e2f55f31',
    brand: 'BMW',
    year: 1967,
    color: 'Silver',
  },
  {
    vin: '11274338',
    brand: 'Mercedes',
    year: 1999,
    color: 'Blue',
  },
  {
    vin: 'f710e177',
    brand: 'Fiat',
    year: 2007,
    color: 'White',
  },
  {
    vin: 'd8375b4b',
    brand: 'Volvo',
    year: 1977,
    color: 'Blue',
  },
  {
    vin: 'a27ddfe3',
    brand: 'VW',
    year: 1978,
    color: 'Blue',
  },
  {
    vin: 'd8848162',
    brand: 'BMW',
    year: 2008,
    color: 'Black',
  },
  {
    vin: 'e9cb3677',
    brand: 'BMW',
    year: 2004,
    color: 'Black',
  },
  {
    vin: 'c9dc321d',
    brand: 'BMW',
    year: 1989,
    color: 'Red',
  },
  {
    vin: '4c75c610',
    brand: 'Volvo',
    year: 1972,
    color: 'Yellow',
  },
  {
    vin: '1c90c93d',
    brand: 'Audi',
    year: 2004,
    color: 'Silver',
  },
  {
    vin: '5ccc9f7f',
    brand: 'Jaguar',
    year: 1961,
    color: 'Red',
  },
  {
    vin: '94498bc0',
    brand: 'Fiat',
    year: 1965,
    color: 'Silver',
  },
  {
    vin: '1d1a21f3',
    brand: 'Honda',
    year: 1985,
    color: 'Red',
  },
  {
    vin: 'ea463ad3',
    brand: 'BMW',
    year: 1992,
    color: 'Blue',
  },
  {
    vin: 'c24bdeb2',
    brand: 'Honda',
    year: 1991,
    color: 'Red',
  },
  {
    vin: 'af3b744b',
    brand: 'Audi',
    year: 1998,
    color: 'Green',
  },
  {
    vin: 'bebd5a96',
    brand: 'Jaguar',
    year: 1989,
    color: 'Black',
  },
  {
    vin: '6ef9dbf3',
    brand: 'Fiat',
    year: 1962,
    color: 'Orange',
  },
  {
    vin: 'eede8f1e',
    brand: 'Jaguar',
    year: 1977,
    color: 'Brown',
  },
  {
    vin: '9d11b02d',
    brand: 'BMW',
    year: 1971,
    color: 'Yellow',
  },
  {
    vin: '1d4223a1',
    brand: 'Mercedes',
    year: 1975,
    color: 'Brown',
  },
  {
    vin: '4d118346',
    brand: 'Mercedes',
    year: 1985,
    color: 'Brown',
  },
  {
    vin: 'cce76f06',
    brand: 'Honda',
    year: 1980,
    color: 'Maroon',
  },
  {
    vin: '2af398ed',
    brand: 'Renault',
    year: 1970,
    color: 'Yellow',
  },
  {
    vin: 'c0ddab4c',
    brand: 'Audi',
    year: 2003,
    color: 'Silver',
  },
  {
    vin: 'a27ea639',
    brand: 'Mercedes',
    year: 1968,
    color: 'Yellow',
  },
  {
    vin: 'e6441f09',
    brand: 'Jaguar',
    year: 1982,
    color: 'Green',
  },
  {
    vin: 'c4c59d58',
    brand: 'Fiat',
    year: 2005,
    color: 'Orange',
  },
  {
    vin: '9d31fc0a',
    brand: 'Mercedes',
    year: 1974,
    color: 'Brown',
  },
  {
    vin: 'b0ffce2d',
    brand: 'Volvo',
    year: 1966,
    color: 'Yellow',
  },
  {
    vin: 'ca7e52e3',
    brand: 'Honda',
    year: 1971,
    color: 'Orange',
  },
  {
    vin: '56b36f0e',
    brand: 'Mercedes',
    year: 2008,
    color: 'Orange',
  },
  {
    vin: 'ba045e1e',
    brand: 'Jaguar',
    year: 1968,
    color: 'White',
  },
  {
    vin: 'fd579989',
    brand: 'BMW',
    year: 1975,
    color: 'Black',
  },
  {
    vin: '084850a3',
    brand: 'Audi',
    year: 1990,
    color: 'Red',
  },
  {
    vin: 'e39245ab',
    brand: 'BMW',
    year: 1969,
    color: 'White',
  },
  {
    vin: '41ab14a1',
    brand: 'Jaguar',
    year: 1987,
    color: 'Silver',
  },
  {
    vin: '7ec4c1c0',
    brand: 'Jaguar',
    year: 1980,
    color: 'Black',
  },
  {
    vin: 'bf1c14aa',
    brand: 'Audi',
    year: 1984,
    color: 'Yellow',
  },
  {
    vin: 'adeff567',
    brand: 'Volvo',
    year: 2000,
    color: 'Brown',
  },
  {
    vin: '61e5e07d',
    brand: 'Mercedes',
    year: 1978,
    color: 'Orange',
  },
  {
    vin: '7555e46a',
    brand: 'Audi',
    year: 1966,
    color: 'Blue',
  },
  {
    vin: '95babbd1',
    brand: 'Honda',
    year: 1998,
    color: 'Black',
  },
  {
    vin: 'ff6885f7',
    brand: 'Audi',
    year: 1996,
    color: 'White',
  },
  {
    vin: '5b5a0031',
    brand: 'Audi',
    year: 1968,
    color: 'Brown',
  },
  {
    vin: 'de63c575',
    brand: 'Mercedes',
    year: 1989,
    color: 'Yellow',
  },
  {
    vin: '6bf3bfbc',
    brand: 'Audi',
    year: 1968,
    color: 'Green',
  },
  {
    vin: 'd2d2e8d4',
    brand: 'Fiat',
    year: 1985,
    color: 'Green',
  },
  {
    vin: 'edcab1f7',
    brand: 'VW',
    year: 1979,
    color: 'Silver',
  },
  {
    vin: '03234e20',
    brand: 'Mercedes',
    year: 1962,
    color: 'Orange',
  },
  {
    vin: 'de2a7b08',
    brand: 'Honda',
    year: 2007,
    color: 'Blue',
  },
  {
    vin: '717b8282',
    brand: 'BMW',
    year: 1999,
    color: 'Yellow',
  },
  {
    vin: '790e7f03',
    brand: 'Volvo',
    year: 1983,
    color: 'White',
  },
  {
    vin: '8eefb223',
    brand: 'Jaguar',
    year: 1983,
    color: 'Silver',
  },
  {
    vin: '5e524acd',
    brand: 'Jaguar',
    year: 1994,
    color: 'Maroon',
  },
  {
    vin: '26b1aff9',
    brand: 'BMW',
    year: 1965,
    color: 'Black',
  },
  {
    vin: 'c007a623',
    brand: 'Renault',
    year: 1968,
    color: 'Maroon',
  },
  {
    vin: '76733e83',
    brand: 'Honda',
    year: 1991,
    color: 'White',
  },
  {
    vin: 'ef3c14f7',
    brand: 'Fiat',
    year: 1987,
    color: 'Brown',
  },
  {
    vin: '2b4ca005',
    brand: 'Honda',
    year: 2009,
    color: 'Silver',
  },
  {
    vin: '8191dbb6',
    brand: 'BMW',
    year: 2005,
    color: 'Black',
  },
  {
    vin: 'f6b3bd94',
    brand: 'Renault',
    year: 1967,
    color: 'Yellow',
  },
  {
    vin: 'abb19f41',
    brand: 'Volvo',
    year: 1975,
    color: 'Blue',
  },
  {
    vin: '7470c95f',
    brand: 'Renault',
    year: 1996,
    color: 'Black',
  },
  {
    vin: '5f1b57a3',
    brand: 'Volvo',
    year: 1986,
    color: 'Red',
  },
  {
    vin: 'ed47a74b',
    brand: 'BMW',
    year: 2007,
    color: 'Brown',
  },
  {
    vin: 'ed6030f7',
    brand: 'Honda',
    year: 1990,
    color: 'Red',
  },
  {
    vin: '944c71dc',
    brand: 'Mercedes',
    year: 1991,
    color: 'Silver',
  },
  {
    vin: 'c7d838a5',
    brand: 'VW',
    year: 1980,
    color: 'Yellow',
  },
  {
    vin: '712db898',
    brand: 'Audi',
    year: 1965,
    color: 'Red',
  },
  {
    vin: '99acc06f',
    brand: 'BMW',
    year: 1995,
    color: 'Silver',
  },
  {
    vin: '6c68ffa5',
    brand: 'Jaguar',
    year: 1999,
    color: 'Green',
  },
  {
    vin: '63893922',
    brand: 'Renault',
    year: 1991,
    color: 'Brown',
  },
  {
    vin: 'dca5f739',
    brand: 'Jaguar',
    year: 2002,
    color: 'Blue',
  },
  {
    vin: '16da6dcb',
    brand: 'Jaguar',
    year: 2006,
    color: 'Blue',
  },
  {
    vin: 'fe9ca30c',
    brand: 'Fiat',
    year: 1967,
    color: 'Maroon',
  },
  {
    vin: 'f0193ac7',
    brand: 'Mercedes',
    year: 1979,
    color: 'Orange',
  },
  {
    vin: '145f5551',
    brand: 'Jaguar',
    year: 1993,
    color: 'Brown',
  },
  {
    vin: '24714317',
    brand: 'Mercedes',
    year: 1971,
    color: 'White',
  },
  {
    vin: '1a9c6e4e',
    brand: 'Jaguar',
    year: 1997,
    color: 'Yellow',
  },
  {
    vin: 'c9b7ef72',
    brand: 'Fiat',
    year: 1992,
    color: 'Maroon',
  },
  {
    vin: 'b1b6c375',
    brand: 'Fiat',
    year: 1963,
    color: 'Silver',
  },
  {
    vin: '7254a003',
    brand: 'Audi',
    year: 1982,
    color: 'White',
  },
  {
    vin: '6f0de80f',
    brand: 'Renault',
    year: 1987,
    color: 'Blue',
  },
  {
    vin: 'e3048f87',
    brand: 'Fiat',
    year: 1989,
    color: 'Blue',
  },
  {
    vin: '361e435a',
    brand: 'BMW',
    year: 1973,
    color: 'Green',
  },
  {
    vin: '59e6a9f3',
    brand: 'BMW',
    year: 1964,
    color: 'Maroon',
  },
  {
    vin: 'b791fe05',
    brand: 'Mercedes',
    year: 1993,
    color: 'Yellow',
  },
  {
    vin: '68b0dd88',
    brand: 'BMW',
    year: 2002,
    color: 'Green',
  },
  {
    vin: '5b439d1f',
    brand: 'BMW',
    year: 1964,
    color: 'Maroon',
  },
  {
    vin: '9a7ac9e3',
    brand: 'Renault',
    year: 1988,
    color: 'White',
  },
  {
    vin: 'd214751d',
    brand: 'Honda',
    year: 1997,
    color: 'White',
  },
  {
    vin: '72229390',
    brand: 'Mercedes',
    year: 1996,
    color: 'White',
  },
  {
    vin: 'b5fbbeee',
    brand: 'VW',
    year: 1999,
    color: 'Brown',
  },
  {
    vin: '8972b543',
    brand: 'Audi',
    year: 1973,
    color: 'Black',
  },
  {
    vin: '7bc21024',
    brand: 'Renault',
    year: 1980,
    color: 'Yellow',
  },
  {
    vin: '5d661964',
    brand: 'Renault',
    year: 2005,
    color: 'Silver',
  },
  {
    vin: 'a6ccc2d8',
    brand: 'Honda',
    year: 1994,
    color: 'Blue',
  },
  {
    vin: 'c1f15f28',
    brand: 'Volvo',
    year: 1999,
    color: 'Black',
  },
  {
    vin: '161512ce',
    brand: 'VW',
    year: 1962,
    color: 'Black',
  },
  {
    vin: '16e0b448',
    brand: 'Fiat',
    year: 1990,
    color: 'Green',
  },
  {
    vin: 'f0734442',
    brand: 'Audi',
    year: 1966,
    color: 'Orange',
  },
  {
    vin: '5e233279',
    brand: 'Audi',
    year: 1964,
    color: 'Green',
  },
  {
    vin: '1de720b2',
    brand: 'Renault',
    year: 2003,
    color: 'Orange',
  },
  {
    vin: '46efaeb2',
    brand: 'Jaguar',
    year: 1993,
    color: 'Green',
  },
  {
    vin: '88f2354c',
    brand: 'Jaguar',
    year: 2006,
    color: 'Black',
  },
  {
    vin: '04819fd6',
    brand: 'Mercedes',
    year: 1983,
    color: 'White',
  },
  {
    vin: '401771c8',
    brand: 'Volvo',
    year: 1962,
    color: 'Silver',
  },
  {
    vin: '8600877b',
    brand: 'VW',
    year: 1996,
    color: 'Black',
  },
  {
    vin: '946bd645',
    brand: 'Honda',
    year: 1991,
    color: 'Red',
  },
  {
    vin: 'ad078e69',
    brand: 'Fiat',
    year: 1991,
    color: 'Brown',
  },
  {
    vin: '93138901',
    brand: 'Mercedes',
    year: 1961,
    color: 'Silver',
  },
  {
    vin: 'f365dfa4',
    brand: 'Mercedes',
    year: 1980,
    color: 'Black',
  },
  {
    vin: '22647161',
    brand: 'Audi',
    year: 2007,
    color: 'Blue',
  },
  {
    vin: '92d1ee27',
    brand: 'Jaguar',
    year: 1977,
    color: 'Silver',
  },
  {
    vin: '137c2b3a',
    brand: 'Honda',
    year: 1970,
    color: 'Blue',
  },
  {
    vin: 'b05b5235',
    brand: 'BMW',
    year: 1967,
    color: 'Yellow',
  },
  {
    vin: '1afbf400',
    brand: 'Audi',
    year: 1966,
    color: 'Maroon',
  },
  {
    vin: '8530ae50',
    brand: 'BMW',
    year: 1979,
    color: 'Brown',
  },
  {
    vin: 'c9a487a3',
    brand: 'Volvo',
    year: 1981,
    color: 'Silver',
  },
  {
    vin: '5cb0bed6',
    brand: 'Honda',
    year: 1962,
    color: 'Orange',
  },
  {
    vin: 'cf7d0b45',
    brand: 'Fiat',
    year: 1997,
    color: 'Green',
  },
  {
    vin: 'bc762dd0',
    brand: 'Jaguar',
    year: 2000,
    color: 'Yellow',
  },
  {
    vin: '97207a61',
    brand: 'VW',
    year: 1976,
    color: 'Blue',
  },
  {
    vin: '17680899',
    brand: 'Mercedes',
    year: 2006,
    color: 'Silver',
  },
  {
    vin: 'd8a98d30',
    brand: 'Renault',
    year: 1990,
    color: 'Green',
  },
  {
    vin: 'ff01ead0',
    brand: 'Audi',
    year: 1962,
    color: 'Blue',
  },
  {
    vin: '38b30a61',
    brand: 'Fiat',
    year: 1977,
    color: 'White',
  },
  {
    vin: '9a6793c1',
    brand: 'Renault',
    year: 1983,
    color: 'Red',
  },
  {
    vin: 'b1f27273',
    brand: 'Mercedes',
    year: 2007,
    color: 'Brown',
  },
  {
    vin: '0fa8c1aa',
    brand: 'Jaguar',
    year: 1982,
    color: 'Blue',
  },
  {
    vin: 'a7520f42',
    brand: 'Volvo',
    year: 2008,
    color: 'Maroon',
  },
  {
    vin: '494eba81',
    brand: 'BMW',
    year: 1966,
    color: 'Silver',
  },
  {
    vin: '683535b8',
    brand: 'Renault',
    year: 2003,
    color: 'White',
  },
  {
    vin: '62e5d216',
    brand: 'Audi',
    year: 1962,
    color: 'Orange',
  },
  {
    vin: '16a65b56',
    brand: 'Jaguar',
    year: 2009,
    color: 'Blue',
  },
  {
    vin: 'd00250a3',
    brand: 'BMW',
    year: 1978,
    color: 'Blue',
  },
  {
    vin: 'f3c3909d',
    brand: 'Renault',
    year: 2003,
    color: 'Green',
  },
];

export const griddata = [
  {
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1001',
    code: 'nvklal433',
    name: 'Black Watch',
    description: 'Product Description',
    image: 'black-watch.jpg',
    price: 72,
    category: 'Accessories',
    quantity: 61,
    inventoryStatus: 'OUTOFSTOCK',
    rating: 4,
  },
  {
    id: '1002',
    code: 'zz21cz3c1',
    name: 'Blue Band',
    description: 'Product Description',
    image: 'blue-band.jpg',
    price: 79,
    category: 'Fitness',
    quantity: 2,
    inventoryStatus: 'LOWSTOCK',
    rating: 3,
  },
  {
    id: '1003',
    code: '244wgerg2',
    name: 'Blue T-Shirt',
    description: 'Product Description',
    image: 'blue-t-shirt.jpg',
    price: 29,
    category: 'Clothing',
    quantity: 25,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1004',
    code: 'h456wer53',
    name: 'Bracelet',
    description: 'Product Description',
    image: 'bracelet.jpg',
    price: 15,
    category: 'Accessories',
    quantity: 73,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1005',
    code: 'av2231fwg',
    name: 'Brown Purse',
    description: 'Product Description',
    image: 'brown-purse.jpg',
    price: 120,
    category: 'Accessories',
    quantity: 0,
    inventoryStatus: 'OUTOFSTOCK',
    rating: 4,
  },
  {
    id: '1006',
    code: 'bib36pfvm',
    name: 'Chakra Bracelet',
    description: 'Product Description',
    image: 'chakra-bracelet.jpg',
    price: 32,
    category: 'Accessories',
    quantity: 5,
    inventoryStatus: 'LOWSTOCK',
    rating: 3,
  },
  {
    id: '1007',
    code: 'mbvjkgip5',
    name: 'Galaxy Earrings',
    description: 'Product Description',
    image: 'galaxy-earrings.jpg',
    price: 34,
    category: 'Accessories',
    quantity: 23,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1008',
    code: 'vbb124btr',
    name: 'Game Controller',
    description: 'Product Description',
    image: 'game-controller.jpg',
    price: 99,
    category: 'Electronics',
    quantity: 2,
    inventoryStatus: 'LOWSTOCK',
    rating: 4,
  },
  {
    id: '1009',
    code: 'cm230f032',
    name: 'Gaming Set',
    description: 'Product Description',
    image: 'gaming-set.jpg',
    price: 299,
    category: 'Electronics',
    quantity: 63,
    inventoryStatus: 'INSTOCK',
    rating: 3,
  },
  {
    id: '1010',
    code: 'plb34234v',
    name: 'Gold Phone Case',
    description: 'Product Description',
    image: 'gold-phone-case.jpg',
    price: 24,
    category: 'Accessories',
    quantity: 0,
    inventoryStatus: 'OUTOFSTOCK',
    rating: 4,
  },
  {
    id: '1011',
    code: '4920nnc2d',
    name: 'Green Earbuds',
    description: 'Product Description',
    image: 'green-earbuds.jpg',
    price: 89,
    category: 'Electronics',
    quantity: 23,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1012',
    code: '250vm23cc',
    name: 'Green T-Shirt',
    description: 'Product Description',
    image: 'green-t-shirt.jpg',
    price: 49,
    category: 'Clothing',
    quantity: 74,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1013',
    code: 'fldsmn31b',
    name: 'Grey T-Shirt',
    description: 'Product Description',
    image: 'grey-t-shirt.jpg',
    price: 48,
    category: 'Clothing',
    quantity: 0,
    inventoryStatus: 'OUTOFSTOCK',
    rating: 3,
  },
  {
    id: '1014',
    code: 'waas1x2as',
    name: 'Headphones',
    description: 'Product Description',
    image: 'headphones.jpg',
    price: 175,
    category: 'Electronics',
    quantity: 8,
    inventoryStatus: 'LOWSTOCK',
    rating: 5,
  },
  {
    id: '1015',
    code: 'vb34btbg5',
    name: 'Light Green T-Shirt',
    description: 'Product Description',
    image: 'light-green-t-shirt.jpg',
    price: 49,
    category: 'Clothing',
    quantity: 34,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1016',
    code: 'k8l6j58jl',
    name: 'Lime Band',
    description: 'Product Description',
    image: 'lime-band.jpg',
    price: 79,
    category: 'Fitness',
    quantity: 12,
    inventoryStatus: 'INSTOCK',
    rating: 3,
  },
  {
    id: '1017',
    code: 'v435nn85n',
    name: 'Mini Speakers',
    description: 'Product Description',
    image: 'mini-speakers.jpg',
    price: 85,
    category: 'Clothing',
    quantity: 42,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1018',
    code: '09zx9c0zc',
    name: 'Painted Phone Case',
    description: 'Product Description',
    image: 'painted-phone-case.jpg',
    price: 56,
    category: 'Accessories',
    quantity: 41,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1019',
    code: 'mnb5mb2m5',
    name: 'Pink Band',
    description: 'Product Description',
    image: 'pink-band.jpg',
    price: 79,
    category: 'Fitness',
    quantity: 63,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1020',
    code: 'r23fwf2w3',
    name: 'Pink Purse',
    description: 'Product Description',
    image: 'pink-purse.jpg',
    price: 110,
    category: 'Accessories',
    quantity: 0,
    inventoryStatus: 'OUTOFSTOCK',
    rating: 4,
  },
  {
    id: '1021',
    code: 'pxpzczo23',
    name: 'Purple Band',
    description: 'Product Description',
    image: 'purple-band.jpg',
    price: 79,
    category: 'Fitness',
    quantity: 6,
    inventoryStatus: 'LOWSTOCK',
    rating: 3,
  },
  {
    id: '1022',
    code: '2c42cb5cb',
    name: 'Purple Gemstone Necklace',
    description: 'Product Description',
    image: 'purple-gemstone-necklace.jpg',
    price: 45,
    category: 'Accessories',
    quantity: 62,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1023',
    code: '5k43kkk23',
    name: 'Purple T-Shirt',
    description: 'Product Description',
    image: 'purple-t-shirt.jpg',
    price: 49,
    category: 'Clothing',
    quantity: 2,
    inventoryStatus: 'LOWSTOCK',
    rating: 5,
  },
  {
    id: '1024',
    code: 'lm2tny2k4',
    name: 'Shoes',
    description: 'Product Description',
    image: 'shoes.jpg',
    price: 64,
    category: 'Clothing',
    quantity: 0,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1025',
    code: 'nbm5mv45n',
    name: 'Sneakers',
    description: 'Product Description',
    image: 'sneakers.jpg',
    price: 78,
    category: 'Clothing',
    quantity: 52,
    inventoryStatus: 'INSTOCK',
    rating: 4,
  },
  {
    id: '1026',
    code: 'zx23zc42c',
    name: 'Teal T-Shirt',
    description: 'Product Description',
    image: 'teal-t-shirt.jpg',
    price: 49,
    category: 'Clothing',
    quantity: 3,
    inventoryStatus: 'LOWSTOCK',
    rating: 3,
  },
  {
    id: '1027',
    code: 'acvx872gc',
    name: 'Yellow Earbuds',
    description: 'Product Description',
    image: 'yellow-earbuds.jpg',
    price: 89,
    category: 'Electronics',
    quantity: 35,
    inventoryStatus: 'INSTOCK',
    rating: 3,
  },
  {
    id: '1028',
    code: 'tx125ck42',
    name: 'Yoga Mat',
    description: 'Product Description',
    image: 'yoga-mat.jpg',
    price: 20,
    category: 'Fitness',
    quantity: 15,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1029',
    code: 'gwuby345v',
    name: 'Yoga Set',
    description: 'Product Description',
    image: 'yoga-set.jpg',
    price: 20,
    category: 'Fitness',
    quantity: 25,
    inventoryStatus: 'INSTOCK',
    rating: 8,
  },
];

export const other1 = [
  {
    key: '0',
    label: 'Documents',
    data: 'Documents Folder',
    icon: 'pi pi-fw pi-inbox',
    children: [
      {
        key: '0-0',
        label: 'Work',
        data: 'Work Folder',
        icon: 'pi pi-fw pi-cog',
        children: [
          {
            key: '0-0-0',
            label: 'Expenses.doc',
            icon: 'pi pi-fw pi-file',
            data: 'Expenses Document',
          },
          {
            key: '0-0-1',
            label: 'Resume.doc',
            icon: 'pi pi-fw pi-file',
            data: 'Resume Document',
          },
        ],
      },
      {
        key: '0-1',
        label: 'Home',
        data: 'Home Folder',
        icon: 'pi pi-fw pi-home',
        children: [
          {
            key: '0-1-0',
            label: 'Invoices.txt',
            icon: 'pi pi-fw pi-file',
            data: 'Invoices for this month',
          },
        ],
      },
    ],
  },
  {
    key: '1',
    label: 'Events',
    data: 'Events Folder',
    icon: 'pi pi-fw pi-calendar',
    children: [
      {
        key: '1-0',
        label: 'Meeting',
        icon: 'pi pi-fw pi-calendar-plus',
        data: 'Meeting',
      },
      {
        key: '1-1',
        label: 'Product Launch',
        icon: 'pi pi-fw pi-calendar-plus',
        data: 'Product Launch',
      },
      {
        key: '1-2',
        label: 'Report Review',
        icon: 'pi pi-fw pi-calendar-plus',
        data: 'Report Review',
      },
    ],
  },
  {
    key: '2',
    label: 'Movies',
    data: 'Movies Folder',
    icon: 'pi pi-fw pi-star-fill',
    children: [
      {
        key: '2-0',
        icon: 'pi pi-fw pi-star-fill',
        label: 'Al Pacino',
        data: 'Pacino Movies',
        children: [
          {
            key: '2-0-0',
            label: 'Scarface',
            icon: 'pi pi-fw pi-video',
            data: 'Scarface Movie',
          },
          {
            key: '2-0-1',
            label: 'Serpico',
            icon: 'pi pi-fw pi-video',
            data: 'Serpico Movie',
          },
        ],
      },
      {
        key: '2-1',
        label: 'Robert De Niro',
        icon: 'pi pi-fw pi-star-fill',
        data: 'De Niro Movies',
        children: [
          {
            key: '2-1-0',
            label: 'Goodfellas',
            icon: 'pi pi-fw pi-video',
            data: 'Goodfellas Movie',
          },
          {
            key: '2-1-1',
            label: 'Untouchables',
            icon: 'pi pi-fw pi-video',
            data: 'Untouchables Movie',
          },
        ],
      },
    ],
  },
];

export const TimelineData = [
  {
    status: 'Ordered',
    date: '15/10/2020 10:30',
    icon: 'pi pi-shopping-cart',
    color: '#9C27B0',
    image: 'game-controller.jpg',
  },
  {
    status: 'Processing',
    date: '15/10/2020 14:00',
    icon: 'pi pi-cog',
    color: '#673AB7',
  },
  {
    status: 'Shipped',
    date: '15/10/2020 16:15',
    icon: 'pi pi-shopping-cart',
    color: '#FF9800',
  },
  {
    status: 'Delivered',
    date: '16/10/2020 10:00',
    icon: 'pi pi-check',
    color: '#607D8B',
  },
];

export const TreenodedataArray = [
  {
    key: '0',
    label: 'Documents',
    data: 'Documents Folder',
    icon: 'pi pi-fw pi-inbox',
    children: [
      {
        key: '0-0',
        label: 'Work',
        data: 'Work Folder',
        icon: 'pi pi-fw pi-cog',
        children: [
          {
            key: '0-0-0',
            label: 'Expenses.doc',
            icon: 'pi pi-fw pi-file',
            data: 'Expenses Document',
          },
          {
            key: '0-0-1',
            label: 'Resume.doc',
            icon: 'pi pi-fw pi-file',
            data: 'Resume Document',
          },
        ],
      },
      {
        key: '0-1',
        label: 'Home',
        data: 'Home Folder',
        icon: 'pi pi-fw pi-home',
        children: [
          {
            key: '0-1-0',
            label: 'Invoices.txt',
            icon: 'pi pi-fw pi-file',
            data: 'Invoices for this month',
          },
        ],
      },
    ],
  },
  {
    key: '1',
    label: 'Events',
    data: 'Events Folder',
    icon: 'pi pi-fw pi-calendar',
    children: [
      {
        key: '1-0',
        label: 'Meeting',
        icon: 'pi pi-fw pi-calendar-plus',
        data: 'Meeting',
      },
      {
        key: '1-1',
        label: 'Product Launch',
        icon: 'pi pi-fw pi-calendar-plus',
        data: 'Product Launch',
      },
      {
        key: '1-2',
        label: 'Report Review',
        icon: 'pi pi-fw pi-calendar-plus',
        data: 'Report Review',
      },
    ],
  },
  {
    key: '2',
    label: 'Movies',
    data: 'Movies Folder',
    icon: 'pi pi-fw pi-star-fill',
    children: [
      {
        key: '2-0',
        icon: 'pi pi-fw pi-star-fill',
        label: 'Al Pacino',
        data: 'Pacino Movies',
        children: [
          {
            key: '2-0-0',
            label: 'Scarface',
            icon: 'pi pi-fw pi-video',
            data: 'Scarface Movie',
          },
          {
            key: '2-0-1',
            label: 'Serpico',
            icon: 'pi pi-fw pi-video',
            data: 'Serpico Movie',
          },
        ],
      },
      {
        key: '2-1',
        label: 'Robert De Niro',
        icon: 'pi pi-fw pi-star-fill',
        data: 'De Niro Movies',
        children: [
          {
            key: '2-1-0',
            label: 'Goodfellas',
            icon: 'pi pi-fw pi-video',
            data: 'Goodfellas Movie',
          },
          {
            key: '2-1-1',
            label: 'Untouchables',
            icon: 'pi pi-fw pi-video',
            data: 'Untouchables Movie',
          },
        ],
      },
    ],
  },
];
